language: node_js

node_js:
- '6'

script:
- npm run ci

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: apifolio@gmail.com
  api_key:
    secure: InaQjxQliDHwREoSxs0oBwCPVq+94qp+SVY8vspmo4dU7E28srIhxqmU0M6uXlRqMS3St7Hq3xVFtdXyAFH8KoMPJ22nP82AYnyZ5Nf+0iU8ieFF7vttVoFHzdm/CiGcG2XsbQeIgFIYupe5Yg4inY9Wnxr2Z+Cn4LzpN8vaEiCcYcVx3++O7vAaj3f2elxtMfdndktEHi6SP44K7YoptUgAfe3/lbP1ttCPbZ5QaJ1HDUHMWR/IP7gIEUr7aiRiwyriDLCZCLH1NjoOLVSU6u3cSX0TUksqqr53ZJOePnO7+wM0O8u+BhWzCNdqIx4qKt5tOOT1Gqixdm+DfrlOV0ODlnAePFY8tsj9mfId3ZzAgLsxTlSdlbkvr2mPXUdY2E9omDoxMwZUqL4ygIMZ0jyg1MwaOYKYu+WDRd+D82LsboX11VCzNGhwBk4Ghw0efg3OuC8Ye7hI0+y7c/k4MU41jtjgGSodPW41FrynaXk1y8TfmrbDNGW7KIsvGqN1DatrR+pVM3SH7DgCOtIf9sdtlh/hpTjov2WXwTIqLkpygvT8lGSSROok87ZChi/NRZ8kwia2diWgD0Xv6UaQ/mfr4qUddmkkxeCbtx0ES3p7gkbT4dTJ4iFt6l0Ik+OPjpUG5BN9M1ADtCtuI1EjhDgfUUgRt5XgtdgrCHS3h3Y=
  tag: next
