language: node_js
node_js: node
env: NODE_ENV=test

before_script:
- npm run build

script:
- npm run ci

after_success:
- npm run cov

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master